let contaController = new ContaController();
let clienteController = new ClienteController();
contaController.listar();
const c1 = new Conta('1', 100);
const p1 = new Poupanca('2', 100);
const cb1 = new ContaBonificada('3', 0);
console.log('Conta: ' + c1.saldo);
p1.atualizarSaldoAniversario();
console.log('Poupanca: ' + p1.saldo);
cb1.creditar(100);
console.log('Conta Bonificada: ' + cb1.saldo);
const clientes = new Clientes();
clientes.inserir(new Cliente('danilo', '123', c1));
clientes.inserir(new Cliente('miguel', '456', p1));
clientes.inserir(new Cliente('maria', '789', cb1));
console.log(clientes.listar());
clientes.remover('123');
console.log(clientes.listar());
console.log(clientes.pesquisar('456'));
